host: 127.0.0.1
port: 8080
log_level: info
workers: 1
auto_reload: true
cors_allowed_origins: []
cors_allow_credentials: False
cors_allowed_methods: []
cors_allowed_headers: []

drs_self_url: drs://localhost:8080/
api_route: /ga4gh/drs/v1
custom_spec_url: null

rabbitmq_host: "rabbitmq"
rabbitmq_port: 5672
topic_name_stage_request: "non_staged_file_requested"

db_url: postgresql://admin:admin@postgresql/storage
db_print_logs: false

s3_endpoint_url: http://drs3:4566
s3_access_key_id: test
s3_secret_access_key: test
s3_outbox_bucket_id: outbox
